os: linux
dist: bionic
branches:
  except:
    - /^legacy\/.*$/
    - heroku
language: php
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 7.2
  - 7.3
  - 7.4
env:
  global:
    - SOLDER_REPO_LOCATION="$TRAVIS_BUILD_DIR/public/resources/default/"
    - SOLDER_MIRROR_URL="http://mirror.technicpack.net/Technic/"
    - REPO_TYPE="local"
before_install:
  - echo $REPO
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
install: COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-source --no-interaction
before_script:
  - cp .env.testing .env
  - php artisan key:generate
script: vendor/bin/phpunit
